// ai/providers.ts — All provider definitions with their model catalogues.
// The extension calls AI APIs directly from the browser (no proxy needed).

import type { ProviderDef, ProviderId } from "../types";

export const PROVIDERS: ProviderDef[] = [
    {
        id: "openai",
        name: "OpenAI",
        baseURL: "https://api.openai.com/v1",
        apiKeyLabel: "OpenAI API Key",
        apiKeyPlaceholder: "sk-...",
        requiresKey: true,
        format: "openai",
        defaultModel: "gpt-4o-mini",
        models: [
            { id: "gpt-4o", name: "GPT-4o", contextLength: 128000, vision: true },
            { id: "gpt-4o-mini", name: "GPT-4o Mini", contextLength: 128000, vision: true },
            { id: "gpt-4-turbo", name: "GPT-4 Turbo", contextLength: 128000, vision: true },
            { id: "gpt-3.5-turbo", name: "GPT-3.5 Turbo", contextLength: 16385 },
            { id: "o1", name: "o1", contextLength: 200000 },
            { id: "o1-mini", name: "o1 Mini", contextLength: 128000 },
            { id: "o3-mini", name: "o3 Mini", contextLength: 200000 },
        ],
    },
    {
        id: "anthropic",
        name: "Anthropic",
        baseURL: "https://api.anthropic.com/v1",
        apiKeyLabel: "Anthropic API Key",
        apiKeyPlaceholder: "sk-ant-...",
        requiresKey: true,
        format: "anthropic",
        defaultModel: "claude-3-5-haiku-20241022",
        models: [
            { id: "claude-opus-4-5", name: "Claude Opus 4.5", contextLength: 200000, vision: true },
            { id: "claude-sonnet-4-5", name: "Claude Sonnet 4.5", contextLength: 200000, vision: true },
            { id: "claude-3-5-sonnet-20241022", name: "Claude 3.5 Sonnet", contextLength: 200000, vision: true },
            { id: "claude-3-5-haiku-20241022", name: "Claude 3.5 Haiku", contextLength: 200000, vision: true },
            { id: "claude-3-opus-20240229", name: "Claude 3 Opus", contextLength: 200000, vision: true },
        ],
    },
    {
        id: "google",
        name: "Google Gemini",
        baseURL: "https://generativelanguage.googleapis.com/v1beta",
        apiKeyLabel: "Google AI API Key",
        apiKeyPlaceholder: "AIza...",
        requiresKey: true,
        format: "google",
        defaultModel: "gemini-2.0-flash",
        models: [
            { id: "gemini-2.0-flash", name: "Gemini 2.0 Flash", contextLength: 1000000, vision: true },
            { id: "gemini-2.0-flash-lite", name: "Gemini 2.0 Flash Lite", contextLength: 1000000 },
            { id: "gemini-2.5-pro-preview-03-25", name: "Gemini 2.5 Pro", contextLength: 1000000, vision: true },
            { id: "gemini-1.5-pro", name: "Gemini 1.5 Pro", contextLength: 2000000, vision: true },
            { id: "gemini-1.5-flash", name: "Gemini 1.5 Flash", contextLength: 1000000, vision: true },
        ],
    },
    {
        id: "groq",
        name: "Groq",
        baseURL: "https://api.groq.com/openai/v1",
        apiKeyLabel: "Groq API Key",
        apiKeyPlaceholder: "gsk_...",
        requiresKey: true,
        format: "openai",
        defaultModel: "llama-3.3-70b-versatile",
        models: [
            { id: "llama-3.3-70b-versatile", name: "Llama 3.3 70B", contextLength: 128000 },
            { id: "llama-3.1-8b-instant", name: "Llama 3.1 8B", contextLength: 128000 },
            { id: "gemma2-9b-it", name: "Gemma 2 9B", contextLength: 8192 },
            { id: "mixtral-8x7b-32768", name: "Mixtral 8x7B", contextLength: 32768 },
            { id: "qwen-qwq-32b", name: "Qwen QwQ 32B", contextLength: 128000 },
        ],
    },
    {
        id: "openrouter",
        name: "OpenRouter",
        baseURL: "https://openrouter.ai/api/v1",
        apiKeyLabel: "OpenRouter API Key",
        apiKeyPlaceholder: "sk-or-...",
        requiresKey: true,
        format: "openai",
        defaultModel: "google/gemini-2.0-flash-001",
        models: [
            { id: "google/gemini-2.0-flash-001", name: "Gemini 2.0 Flash", contextLength: 1000000 },
            { id: "anthropic/claude-3.5-sonnet", name: "Claude 3.5 Sonnet", contextLength: 200000, vision: true },
            { id: "openai/gpt-4o", name: "GPT-4o", contextLength: 128000, vision: true },
            { id: "meta-llama/llama-3.3-70b-instruct", name: "Llama 3.3 70B", contextLength: 131072 },
            { id: "deepseek/deepseek-r1", name: "DeepSeek R1", contextLength: 164000 },
            { id: "mistralai/mistral-large", name: "Mistral Large", contextLength: 128000 },
            { id: "qwen/qwen-2.5-72b-instruct", name: "Qwen 2.5 72B", contextLength: 128000 },
            { id: "inception/mercury-2", name: "Mercury 2", contextLength: 32000 },
        ],
    },
    {
        id: "mistral",
        name: "Mistral",
        baseURL: "https://api.mistral.ai/v1",
        apiKeyLabel: "Mistral API Key",
        apiKeyPlaceholder: "...",
        requiresKey: true,
        format: "openai",
        defaultModel: "mistral-large-latest",
        models: [
            { id: "mistral-large-latest", name: "Mistral Large", contextLength: 131000 },
            { id: "mistral-small-latest", name: "Mistral Small", contextLength: 32000 },
            { id: "codestral-latest", name: "Codestral", contextLength: 32000 },
            { id: "open-mistral-nemo", name: "Mistral Nemo", contextLength: 128000 },
        ],
    },
    {
        id: "deepseek",
        name: "DeepSeek",
        baseURL: "https://api.deepseek.com/v1",
        apiKeyLabel: "DeepSeek API Key",
        apiKeyPlaceholder: "sk-...",
        requiresKey: true,
        format: "openai",
        defaultModel: "deepseek-chat",
        models: [
            { id: "deepseek-chat", name: "DeepSeek Chat (V3)", contextLength: 64000 },
            { id: "deepseek-reasoner", name: "DeepSeek R1", contextLength: 64000 },
        ],
    },
    {
        id: "xai",
        name: "xAI (Grok)",
        baseURL: "https://api.x.ai/v1",
        apiKeyLabel: "xAI API Key",
        apiKeyPlaceholder: "xai-...",
        requiresKey: true,
        format: "openai",
        defaultModel: "grok-2-latest",
        models: [
            { id: "grok-3", name: "Grok 3", contextLength: 131072 },
            { id: "grok-2-latest", name: "Grok 2", contextLength: 131072, vision: true },
            { id: "grok-2-vision-latest", name: "Grok 2 Vision", contextLength: 32768, vision: true },
        ],
    },
    {
        id: "ollama",
        name: "Ollama (local)",
        baseURL: "http://localhost:11434/v1",
        apiKeyLabel: "(no key required)",
        apiKeyPlaceholder: "",
        requiresKey: false,
        format: "openai",
        defaultModel: "llama3.2",
        models: [
            { id: "llama3.2", name: "Llama 3.2 3B", contextLength: 128000 },
            { id: "llama3.2:1b", name: "Llama 3.2 1B", contextLength: 128000 },
            { id: "llama3.1:8b", name: "Llama 3.1 8B", contextLength: 128000 },
            { id: "llama3.1:70b", name: "Llama 3.1 70B", contextLength: 128000 },
            { id: "qwen2.5:7b", name: "Qwen 2.5 7B", contextLength: 32000 },
            { id: "mistral:7b", name: "Mistral 7B", contextLength: 32000 },
            { id: "phi4", name: "Phi-4", contextLength: 16000 },
            { id: "deepseek-r1:8b", name: "DeepSeek R1 8B", contextLength: 64000 },
            { id: "gemma3:9b", name: "Gemma 3 9B", contextLength: 32000 },
        ],
    },
    {
        id: "lmstudio",
        name: "LM Studio (local)",
        baseURL: "http://localhost:1234/v1",
        apiKeyLabel: "(no key required)",
        apiKeyPlaceholder: "",
        requiresKey: false,
        format: "openai",
        defaultModel: "local-model",
        models: [
            { id: "local-model", name: "Auto-detect loaded model", contextLength: 4096 },
        ],
    },
    {
        id: "custom",
        name: "Custom (OpenAI-compatible)",
        baseURL: "",
        apiKeyLabel: "API Key (optional)",
        apiKeyPlaceholder: "optional",
        requiresKey: false,
        format: "openai",
        defaultModel: "custom-model",
        models: [
            { id: "custom-model", name: "Custom model", contextLength: 4096 },
        ],
    },
];

export function getProviderDef(id: ProviderId): ProviderDef {
    return PROVIDERS.find(p => p.id === id) ?? PROVIDERS[0];
}
